[project]
name = "language-model-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.4",
    "ollama>=0.5.1",
    "ruff>=0.12.1",
]
